### ISSUE TITLE
_testImpact Function Not Used

### ISSUE THREAD

**Issue by 0xVonBismarck** [CanzaApps/Baki-contracts#13]
I have noticed we are not using the `_testImpact` function in the mint or repay functions, suggest we use this function to simplify testing the collateralization.

This should replace the code in lines 117 & 143 of the mint function, and 261-290 of the Withdraw function (where we test the impact of the withdrawal) 

Moreover, the code in Lines 117-131 would allow a user to mint beyond the collateral ratio if they have a userNetMint of 0. 

The `require(User[msg.sender].collaterizationRatio >= COLLATERIZATION_RATIO_THRESHOLD, "Insufficient collateral");` in line 143 is only tested if the user has a userNetMint > 0.

Alternatively, we could use a require function like the one used in line 143 at the end of any action where the user is either minting, or withdrawing.

This is important to ensure it will not allow the protocol to become insolvent (i.e. we do not have enough collateral to cover the minted zTokens)

**Comment by David405** [comment]
I believe the require on line 117 limits the user from minting more than their collateral. We could of course change it but I was only avoiding zero sums.

**Comment by 0xVonBismarck** [comment]
Yes understand. However, the core condition is that the user can never take
an action that drops their collateralization ratio below the minimum
threshold.

With that said. Let’s assume the usernetmint is 0 and has no collateral has
been previously deposited.

If the user tries to deposit 100 cUSD and tries to mint 90 zUSD the code
would allow it, even though the collateralization ratio would be
100/90=111%, which is below the minimum of 150%, breaching the condition
above.
